"""empty message

Revision ID: 912d8f642724
Revises: 2e2e82e9597a
Create Date: 2022-03-28 13:56:09.762165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '912d8f642724'
down_revision = '2e2e82e9597a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('subject', sa.String(length=200), nullable=False))
    op.drop_column('question', 'suject')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('suject', sa.VARCHAR(length=200), nullable=False))
    op.drop_column('question', 'subject')
    # ### end Alembic commands ###
